var animalMeta = {
    "a": {name: "Platypus"},
    "b": {name: "Butterfly"},
    "c": {name: "Cat"},
    "d": {name: "Dog"},
    "e": {name: "Elephant"},
    "f": {name: "Falcon"},
    "g": {name: "Heron"},
    "h": {name: "Horse"},
    "i": {name: "Deer"},
    "j": {name: "Ram"},
    "k": {name: "Koala"},
    "l": {name: "Sheep"},
    "m": {name: "Monkey"},
    "n": {name: "Bison"},
    "o": {name: "Squirrel"},
    "p": {name: "Penguin"},
    "q": {name: "Duck"},
    "r": {name: "Rabbit"},
    "s": {name: "Seahorse"},
    "t": {name: "Tiger"},
    "u": {name: "Rhino"},
    "v": {name: "Hippo"},
    "w": {name: "Dolphin"},
    "x": {name: "Bear"},
    "y": {name: "Puffin"},
    "z": {name: "Donkey"},
}